
# #
# default: &default
#   adapter: mysql2
#   encoding: utf8
#   pool: 5
#   username: root
#   password: 123456789
#   socket: /var/run/mysqld/mysqld.sock

# development:
#   <<: *default
#   database: collegenews

# test:
#   <<: *default
#   database: collegenews


default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: franklin
  password:
production:
  <<: *default
  database: collegenews_production
  username: collegenews
  password: <%= ENV['COLLEGENEWS_DATABASE_PASSWORD'] %>
